#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_se="0.0.1"
  jq -n --arg se "$ver_se" '{se: $se}'
}

version "$@"
